name: Lint

on:
  workflow_call:

jobs:
  lint-go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: nixbuild/nix-quick-install-action@v34

      - run: nix run .#lint-go

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: nixbuild/nix-quick-install-action@v34

      - run: nix run .#lint-python

